import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

// Import global styles that apply to the entire application
import './globals.css';

/**
 * Configure Geist Sans font with Next.js font optimization
 * This modern, clean sans-serif font is used as the primary font throughout the application
 */
const geistSans = Geist({
  variable: '--font-geist-sans', // CSS variable name for use in styles
  subsets: ['latin'], // Only load Latin character subset for better performance
});

/**
 * Configure Geist Mono font with Next.js font optimization
 * This monospace font is used for code blocks and technical content
 */
const geistMono = Geist_Mono({
  variable: '--font-geist-mono', // CSS variable name for use in styles
  subsets: ['latin'], // Only load Latin character subset for better performance
});

/**
 * Application metadata used by Next.js for SEO and browser tab information
 * These values should be updated for your specific application
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Root layout component that wraps all pages in the application
 * This component provides the HTML and body structure and applies font variables
 * 
 * @param {PropsWithChildren} props - Contains the children components to render within the layout
 * @returns {JSX.Element} The root layout structure with applied fonts
 */
export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
    </html>
  );
}
